# set repo sync
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  # name combined with namespace must not exceed 63 characters
  # name: folder # kpt-set: ${folder}
  name: repo-sync
  namespace: project-id-12345-tier3 # kpt-set: ${project-id}-${folder}
spec:
  sourceFormat: unstructured
  git:
    repo: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME # kpt-set: ${repo-url}
    branch: main # kpt-set: ${repo-branch}
    dir: tier3/deploy/prod # kpt-set: ${repo-dir}
    revision: HEAD # kpt-set: ${version}
    auth: token
    secretRef:
      name: git-creds
