# Repo sync
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  # name combined with namespace must not exceed 63 characters
  # name: folder # kpt-set: ${folder}
  name: repo-sync
  namespace: project-id-folder # kpt-set: ${project-id}-${folder}
spec:
  sourceFormat: unstructured
  git:
    repo: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME # kpt-set: ${repo-url}
    branch: main # kpt-set: ${repo-branch}
    dir: tier4/configcontroller/deploy/<env> # kpt-set: ${repo-dir}
    revision: 0.0.0 # kpt-set: ${version}
    auth: token
    secretRef:
      name: git-creds
