apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  # Used for naming of the root-sync
  ## id : <project-id>
  id: project-id-12345

  # Git repo values
  repo-url: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME
  # repo-url: https://github.com/GITHUB-ORG/REPO-NAME # Alternate, GitHub
  repo-branch: main
  # The `x-fleet-id` is the GCP project-id where the kubernetes clusters are deployed with character "x" as the environment code because this folder will contain the configuration for all environments.
  repo-dir: tier3/kubernetes/_X-FLEET-ID/deploy/dev
