apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  # Repo and namespace naming
  ## project-id
  project-id: project-id-12345
   ## Folder: 'tier3' or 'tier4'
  folder: tier3
  # set git repo values
  repo-url: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME
  # repo-url: https://github.com/GITHUB-ORG/REPO-NAME # Alternate, GitHub
  repo-branch: main
  repo-dir: tier3/configcontroller/deploy/dev
