# set repo sync
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  # name combined with namespace must not exceed 63 characters
  name: repo-sync
  namespace: namespace # kpt-set: ${namespace}
spec:
  sourceFormat: unstructured
  git:
    repo: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME # kpt-set: ${repo-url}
    branch: main # kpt-set: ${repo-branch}
    dir: tier4/kubernetes/<fleet-id>/namespace/deploy/<env>/<namespace> # kpt-set: ${repo-dir}
    revision: 0.0.0 # kpt-set: ${version}
    auth: token
    secretRef:
      name: git-creds
